# Normal scanner worker setup
# Please don't modify this file as your changes might be overwritten with
# the next update.
#
# You can modify 'local.d/worker-normal.inc' to add and merge
# parameters defined inside this section
#
# You can modify 'override.d/worker-normal.inc' to strictly override all
# parameters defined inside this section
#
# See https://rspamd.com/doc/faq.html#what-are-the-locald-and-overrided-directories
# for details
# Module documentation: https://rspamd.com/doc/workers/normal.html

mime = true;
