.TH "RSPAMD" "8" "" "Rspamd User Manual" ""
.SH NAME
.PP
rspamd \- main daemon for rapid spam filtering system
.SH SYNOPSIS
.PP
rspamd [\f[I]options\f[]]...
.PP
rspamd \-\-help
.SH DESCRIPTION
.PP
Rspamd filtering system is designed to be fast, modular and easily
scalable system.
Rspamd core is written in \f[C]C\f[] language using event driven
processing model.
Plugins for rspamd can be written in \f[C]Lua\f[] programming language.
Rspamd is designed to process connections completely asynchronous and do
not block anywhere in code.
.SH OPTIONS
.TP
.B \-f, \-\-no\-fork
Do not daemonize main process
.RS
.RE
.TP
.B \-c \f[I]path\f[], \-\-config=\f[I]path\f[]
Specify config file(s)
.RS
.RE
.TP
.B \-u \f[I]username\f[], \-\-user=\f[I]username\f[]
User to run rspamd as
.RS
.RE
.TP
.B \-g \f[I]groupname\f[], \-\-group=\f[I]groupname\f[]
Group to run rspamd as
.RS
.RE
.TP
.B \-p \f[I]path\f[], \-\-pid=\f[I]path\f[]
Path to pidfile
.RS
.RE
.TP
.B \-i, \-\-insecure
Ignore running workers as privileged users (insecure)
.RS
.RE
.SH EXAMPLES
.PP
Run rspamd daemon with default configuration:
.IP
.nf
\f[C]
rspamd
\f[]
.fi
.PP
Run rspamd in foreground with custom configuration:
.IP
.nf
\f[C]
rspamd\ \-f\ \-c\ ~/rspamd.conf
\f[]
.fi
.PP
Run rspamd specifying user and group:
.IP
.nf
\f[C]
rspamd\ \-u\ rspamd\ \-g\ rspamd\ \-c\ /etc/rspamd/rspamd.conf
\f[]
.fi
.SH SEE ALSO
.PP
Rspamd documentation and source codes may be downloaded from
<https://rspamd.com/>.
