#!/bin/sh
set -e

case "$1" in
    configure)
       SERVER_HOME=/var/lib/rspamd
       SERVER_LOG=/var/log/rspamd
       SERVER_USER=_rspamd

       adduser --quiet \
               --system \
               --group \
               --home $SERVER_HOME \
               --no-create-home \
               --disabled-login \
               --gecos "rspamd spam filtering system" \
               --force-badname \
               $SERVER_USER

       chown $SERVER_USER: $SERVER_HOME $SERVER_LOG
    ;;

    abort-*)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x /etc/init.d/rspamd ]; then
    update-rc.d rspamd defaults >/dev/null
    if [ -d /run/systemd/system ]; then
        deb-systemd-invoke --system daemon-reload >/dev/null || true
        deb-systemd-invoke --system stop rspamd.service 2>/dev/null || true
    else
        invoke-rc.d rspamd start || exit $?
    fi
fi

#DEBHELPER#

exit 0
