#!/bin/sh
#DEBHELPER#

set -e

case "$1" in
    configure)
       SERVER_HOME=/var/lib/rspamd
       SERVER_LOG=/var/log/rspamd
       SERVER_USER=rspamd
       SERVER_NAME="Rspamd spam filtering system"

       adduser --quiet \
               --system \
               --group \
               --home $SERVER_HOME \
               --no-create-home \
               --disabled-login \
               --gecos "$SERVER_NAME" \
               $SERVER_USER

       chown -R $SERVER_USER:$SERVER_GROUP $SERVER_HOME $SERVER_LOG
       chmod u=rwx,g=rx,o= $SERVER_HOME
       chmod u=rwx,g=rx,o=rx $SERVER_LOG
    ;;

    abort-*)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
