#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
   update-rc.d rspamd remove >/dev/null
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

#DEBHELPER#

case "$1" in
    purge)
      rm -rf /var/lib/rspamd
      rm -rf /var/log/rspamd
      rm -rf /run/rspamd
      exit 0;;
    remove|upgrade|disappear|failed-upgrade|abort-*)
      exit 0;;
    *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1;;
esac
