#!/bin/sh
set -e

case "$1" in
    configure)
       SERVER_HOME=/var/lib/rspamd
       SERVER_LOG=/var/log/rspamd
       SERVER_USER=_rspamd

       adduser --quiet \
               --system \
               --group \
               --home $SERVER_HOME \
               --no-create-home \
               --disabled-login \
               --gecos "rspamd spam filtering system" \
               --force-badname \
               $SERVER_USER
       mkdir -p $SERVER_HOME $SERVER_LOG || true
       chown $SERVER_USER: $SERVER_HOME $SERVER_LOG
    ;;

    abort-*)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
