#!/bin/sh
# preinst script for rspamd
#DEBHELPER#

set -e

case "$1" in
    install)
       SERVER_HOME=/var/lib/rspamd
       SERVER_RUN=/var/run/rspamd
       SERVER_LOG=/var/log/rspamd
       SERVER_USER=rspamd
       SERVER_NAME="Rspamd spam filtering system"

       adduser --quiet \
               --system \
               --group \
               --home $SERVER_HOME \
               --no-create-home \
               --disabled-login \
               --gecos "$SERVER_NAME" \
               $SERVER_USER

       # 2. create homedir if not existing
       test -d $SERVER_HOME || mkdir $SERVER_HOME
       test -d $SERVER_RUN || mkdir $SERVER_RUN
       test -d $SERVER_LOG || mkdir $SERVER_LOG

       # 5. adjust file and directory permissions
       if ! dpkg-statoverride --list $SERVER_HOME >/dev/null
       then
           chown -R $SERVER_USER:$SERVER_GROUP $SERVER_HOME $SERVER_LOG $SERVER_RUN
           chmod u=rwx,g=rx,o= $SERVER_HOME
           chmod u=rwx,g=rx,o=rx $SERVER_RUN
           chmod u=rwx,g=rx,o=rx $SERVER_LOG
       fi
    ;;

    abort-upgrade|upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
