name: ci_eslint

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Show installed packages
        run: npm ls

      - name: Run eslint
        run: ./node_modules/.bin/eslint ./

      - name: Run stylelint
        run: ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js
